export const GET_REQUEST_PROFILE = "GET_REQUEST_PROFILE";
export const GET_FAILURE_PROFILE = "GET_FAILURE_PROFILE";

export const GET_SUCCESS_PROFILE = "GET_SUCCESS_PROFILE";

export const ADD_SUCCESS_PROFILE = "ADD_SUCCESS_PROFILE";

export const UPDATE_SUCCESS_PROFILE = "UPDATE_SUCCESS_PROFILE";
export const UPDATE_SUCCESS_PROFILEPIC = "UPDATE_SUCCESS_PROFILEPIC";

export const DELETE_SUCCESS_PROFILE  = "DELETE_SUCCESS_PROFILE";
