export const GET_REQUEST = "GET_REQUEST";
export const GET_FAILURE = "GET_FAILURE";

export const GET_COMMENT = "GET_COMMENT";

export const ADD_COMMENT = "ADD_COMMENT";

export const UPDATE_COMMENT = "UPDATE_COMMENT";

export const DELETE_COMMENT  = "DELETE_COMMENT";

export const GET_COMMENT_REPLY = "GET_COMMENT_REPLY";

export const ADD_COMMENT_REPLY = "ADD_COMMENT_REPLY";